### ISSUE TITLE
Sphinxify licensing

### ISSUE THREAD

**Issue by jasongrout** [spyder-ide/docrepr#20]
I was tracking down the history of the sphinxify licensing to clarify how this sphinxify module is BSD while the [core Sage sphinxify](https://github.com/sagemath/sage/blob/f716a0b366e31bbb546230140489244cfb68390d/src/sage/misc/sphinxify.py) is currently GPLv2+. Here is what I found:
- The sphinxify module was originally created in the Sage Notebook project in 2009 by @TimDumol under the BSD license: https://github.com/sagemath/sagenb/commit/4d96e4e74f34f2fe0131e27917c7d17beb6c93cc#diff-54bafdf5f646af032e48b2e64247d69897aa002b1e039b3984a0d281c08c9ab0. From the commit diff, it appears to have replaced disabled code that called sphinx. See also https://trac.sagemath.org/ticket/7000. Even though the Sage Notebook was under a GPL license, the sphinxify file itself was BSD-licensed.
- Sphinxify gradually evolved in the Sage Notebook codebase, and the file continued to be licensed BSD (https://github.com/sagemath/sagenb/commits/9d04f4bdb6e02bd3e227131b80d5eaf10f09721a/sagenb/misc/sphinxify.py)
- In 2015, @ccordoba12 started what would become the docrepr project and seems to have forked this BSD-licensed sphinxify module: https://github.com/spyder-ide/docrepr/commit/37f2557987acd406d32c72d63081ee1646c89d66#diff-47a8d80ad1d3db4de64b36827a03d3928ba6982bebcc4ea229adce0a3d1c88ad
- So now we have two parallel tracks for sphinxify, one in docrepr and one in Sage.
  - **Sage**: Sphinxify develops further, and in 2016, @jdemeyer forks sphinxify again to create a new version in core Sage: https://github.com/sagemath/sage/commit/4b206a21763c644797a30c48dfe426fc1d43078c#diff-39449f5fec48847286e6bd557d5c4fba2ac5051d7ed3f5b38cb4ac95cdf70d27
    - **Sage Notebook**: The original sphinxify module continues to develop in Sage Notebook (https://github.com/sagemath/sagenb/commits/master/sagenb/misc/sphinxify.py), and in 2019, is deleted and replaced with an import of the core Sage version (https://github.com/sagemath/sagenb/commit/9d04f4bdb6e02bd3e227131b80d5eaf10f09721a#diff-54bafdf5f646af032e48b2e64247d69897aa002b1e039b3984a0d281c08c9ab0)
    - **Core Sage**: The core Sage sphinxify module continues to develop (https://github.com/sagemath/sage/commits/develop/src/sage/misc/sphinxify.py), and in 2018 is relicensed to GPLv2+ with Tim's permission for consistency with the rest of Sage (https://trac.sagemath.org/ticket/26453)
  - **Docrepr**: In Carlos' project, sphinxify continues to be developed as a BSD-licensed module, with its history transitioning over several file renamings. The history of the current file is https://github.com/spyder-ide/docrepr/commits/master/docrepr/sphinxify.py

I don't think there is anything to do and this ticket can be closed immediately, but I just wanted to document the history to prevent confusion.

*Personal side note: If I recall correctly, I remember having a conversation about the BSD license on the original sphinxify module at [SageDays 19](https://wiki.sagemath.org/daysbug2) with Tim and a few others, where we decided it would be fine to have a BSD-licensed file in the Sage Notebook codebase, but that we'd just make sure that file explicitly stated it had the BSD license*

**Comment by CAM-Gerlach** [comment]
Thanks for the very detailed breakdown, @jasongrout !

@ccordoba12 Might be a good idea to add a brief note to the License section of the Readme summarizing this as it directly relates to docrepr and linking here for more information, if @jasongrout wants to submit a PR...but I leave that up to you.

**Comment by SylvainCorlay** [comment]
Should we close this then?

**Comment by CAM-Gerlach** [comment]
I was going to add a mention and a link to this in the Readme in #37

**Comment by ccordoba12** [comment]
Sorry for chiming in so late here, but I'd like to thank @jasongrout for clarifying the licensing situation of this project.

I'd also like to add a bit more context to this part

> In 2015, @ccordoba12 started what would become the docrepr project and seems to have forked this BSD-licensed sphinxify module: 37f2557#diff-47a8d80ad1d3db4de64b36827a03d3928ba6982bebcc4ea229adce0a3d1c88ad

Actually, `docrepr` started as an effort to create an independent project out of the code that powers Spyder's Help pane, so others can be benefit from it. Furthermore, I was the one that created that functionality, which also happens to be my first contribution to Spyder back in 2010.

I found about `sphinxify` at that time when looking for simple libraries that allowed to make webpages out of docstrings on the fly. As @jasongrout mentioned, the license back then was BSD. Since afterwards I didn't merge back changes from Sage's `sphinxify`, there shouldn't be an issue with that.

This is also why the first version of `sphinxify` here is a modified one of the original `sphinxify` in Sage. And there's another version that still lives in Spyder:

https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/help/utils/sphinxify.py

One day we hope to integrate this project with Spyder as well.
