### ISSUE TITLE
Docrepr fails with Sphinx v4

### ISSUE THREAD

**Issue by martinRenou** [spyder-ide/docrepr#26]
It fails for multiple reasons:

- jsmath extension not available anymore: Attempt to fix this in https://github.com/spyder-ide/docrepr/pull/25
- Sphinx's `add_directive` does not accept the `alt` keyword argument

**Comment by CAM-Gerlach** [comment]
> - Sphinx's `add_directive` does not accept the `alt` keyword argument

Seems like what's really going on here is that `add_directive` used to accept `**kwargs` of the directive's options, which I'm guessing is back when it accepted docutils-style function directives rather than the modern class based system, which has been deprecated for many years.

To fix this, you should be able to refactor `plot_directive` into a `Directive` subclass (shouldn't be too complex), moving `run()` under it, and moving the options to `self.option_spec` there, setting the other class attributes as appropriate. See the [Sphinx API docs](https://www.sphinx-doc.org/en/master/extdev/appapi.html?highlight=add_directive#sphinx.application.Sphinx.add_directive) for more details and an example.

**Comment by martinRenou** [comment]
Thanks for your comment :) I will push a fix

**Comment by CAM-Gerlach** [comment]
Thanks, looking forward to it!
